services:
  - type: web
    name: bthwani-backend
    runtime: node    # بدّل env إلى runtime
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
